# Generated by Django 3.0.6 on 2020-05-17 10:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='媒体类型名称')),
            ],
            options={
                'verbose_name': '媒体类型信息',
                'verbose_name_plural': '媒体类型信息',
            },
        ),
        migrations.CreateModel(
            name='CountryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='国家名称')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('continent', models.CharField(choices=[('Asia', '亚洲'), ('Africa', '非洲'), ('Europe', '欧洲'), ('Oceania', '大洋洲'), ('America', '美洲')], max_length=20, verbose_name='所处大洲')),
                ('love_num', models.IntegerField(default=0, verbose_name='收藏数')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击数')),
            ],
            options={
                'verbose_name': '国家信息',
                'verbose_name_plural': '国家信息',
            },
        ),
        migrations.CreateModel(
            name='LanguageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='语种名称')),
            ],
            options={
                'verbose_name': '语种信息',
                'verbose_name_plural': '语种信息',
            },
        ),
        migrations.CreateModel(
            name='MediumInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_image', models.ImageField(max_length=200, upload_to='medium/', verbose_name='媒体徽标')),
                ('chn_name', models.CharField(max_length=30, verbose_name='媒体中文名称')),
                ('en_name', models.CharField(max_length=50, verbose_name='媒体英文名称')),
                ('url', models.URLField(default='http://lichangtai.cn', verbose_name='图片链接')),
                ('desc', models.TextField(verbose_name='媒体简介')),
                ('detail', models.TextField(verbose_name='媒体详情')),
                ('love_num', models.IntegerField(default=0, verbose_name='收藏数')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('category_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mediums.CategoryInfo', verbose_name='所属类别')),
                ('country_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mediums.CountryInfo', verbose_name='所属国家')),
                ('language_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mediums.LanguageInfo', verbose_name='语种')),
            ],
            options={
                'verbose_name': '媒体信息',
                'verbose_name_plural': '媒体信息',
            },
        ),
    ]
