# Generated by Django 3.0.6 on 2020-05-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediuminfo',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='删除状态'),
        ),
        migrations.AlterField(
            model_name='mediuminfo',
            name='url',
            field=models.URLField(default='http://lichangtai.cn', verbose_name='媒体链接'),
        ),
    ]
