# Generated by Django 3.0.6 on 2020-07-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediums', '0002_auto_20200517_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediuminfo',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
